# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compressed_image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compressed_image.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ompressed_image.proto\x12\x0eproto_messages\"3\n\x0f\x43ompressedImage\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\rB\x02\x10\x01\x62\x06proto3'
)




_COMPRESSEDIMAGE = _descriptor.Descriptor(
  name='CompressedImage',
  full_name='proto_messages.CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='proto_messages.CompressedImage.format', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto_messages.CompressedImage.data', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompressedImage = _reflection.GeneratedProtocolMessageType('CompressedImage', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSEDIMAGE,
  '__module__' : 'compressed_image_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.CompressedImage)
  })
_sym_db.RegisterMessage(CompressedImage)


_COMPRESSEDIMAGE.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
